### ISSUE TITLE
Setup keybindings with custom prefix

### ISSUE THREAD

**Issue by Ryckes** [keelerm84/php-refactor-mode.el#3]
Would it be possible to have a custom prefix for keybindings? Like [js2-refactor](https://github.com/magnars/js2-refactor.el#breaking-change-in-060).

**Comment by keelerm84** [comment]
You should be able to define a custom prefix with the current implementation by setting:
````lisp
(setq php-refactor-keymap-prefix (kbd "C-x r"))
````
