### ISSUE TITLE
Initial installation

### ISSUE THREAD

**Issue by RusAlex** [keelerm84/php-refactor-mode.el#4]
I have issues with making it work.

Melpa installation works well. No warnings.

Then in php file I type: 
`php-refactor-mode` and it turns on. In my mode line `PHP/l Refactor FlyC Abbrev`

Then I try to use the package:

`C-c r rv`

It prompts me new variable name

``` emacs
Specify new variable name:
```

Then I type var name and press <RET> 

And something fast appears like small buffer above command line. And then in Status line I see next message: 

`Modifiaction-flag cleared`

And variable still not renamed.

**Comment by keelerm84** [comment]
Can you please provide me with a sample PHP script where you are able to reproduce this problem?  My speculation is there is something failing with the patch command.

Which OS are you using?

**Comment by RusAlex** [comment]
```php
<?php

$foo = 'bar';                                                                                                                  
echo $foo;
```

Im using Fedora OS, and 24.5.1

```bash
~/bin/refactor.phar --version                                                                           
PHP Refactoring Browser version v0.1
```

**Comment by keelerm84** [comment]
Ah.  The rename local variable command only works when the variable is scoped to a method.  This is a limitation of the php-refactoring-browser command.

I can work on trying to improve the error handling though to make this failure more clear.  Thanks for reporting this issue.

**Comment by RusAlex** [comment]
No difference if it's in clas method scope. Result is the same

**Comment by webdevelopers-eu** [comment]
Hello, I am having the same problem and I have realized that the problem is that php-refactor-mode is incompatible with TRAMP mode.

Could you fix it? Editing files over TRAMP is must-have nowadays.

Thanks!

**Comment by pierrelegall** [comment]
Same as @RusAlex described in his first post for me; and without TRAMP.
